### PR TITLE
Mainly Python IOC changes

### PR DESCRIPTION
**Pull request by klemenv**

### CODE REVIEW

**Comment by kasemir** [comment]
Do I need to delete/update examples/23_pythonIOC/python/__pycache__/demo.cpython-38.pyc ?

**Comment by klemenv** [comment]
Yes please.

**Comment by kasemir** [comment]
I think I followed the README.md for adding PyDevice.
```
sudo apt install python-dev
cd /tmp
wget https://github.com/klemenv/PyDevice/archive/refs/tags/R1.1.1.tar.gz
cd /ics/tools
tar zxf /tmp/R1.1.1.tar.gz
cd PyDevice-R1.1.1
ln -snfr /ics/tools/RELEASE.local configure/
make

sudo pip install python-weather
```

There was no error.
But the example doesn't build:

```
$ cd /ics/examples/23_pythonIOC/
training@VB:/ics/examples/23_pythonIOC$ make
make -C ./src install
make[1]: Entering directory '/ics/examples/23_pythonIOC/src'
Makefile:4: /configure/CONFIG.PyDevice: No such file or directory
make[1]: *** No rule to make target '/configure/CONFIG.PyDevice'.  Stop.
make[1]: Leaving directory '/ics/examples/23_pythonIOC/src'
make: *** [/ics/tools/base-7.0.6/configure/RULES_DIRS:85: src.install] Error 2
```

**Comment by klemenv** [comment]
I overlooked that tools/RELEASE.local gets generated. Because the file is in .gitignore, my local changes didn't show up to be committed.

Instructions for PyDevice should be extended with
echo "PYDEVICE=/ics/tools/PyDevice-R1.1.1" > /ics/tools/RELEASE.local
or similar.

**Comment by kasemir** [comment]
Got it. /ics/examples/23_pythonIOC/ now builds.
IOC ends like this:
```
$ cd /ics/examples/iocBoot/ioc_python/
training@VB:/ics/examples/iocBoot/ioc_python$ make
training@VB:/ics/examples/iocBoot/ioc_python$ ./st.cmd 
#!../../bin/linux-x86_64/pyioc
< envPaths
epicsEnvSet("IOC","ioc_python")
epicsEnvSet("TOP","/ics/examples")
epicsEnvSet("EPICS_BASE","/ics/tools/base-7.0.6")
epicsEnvSet("ETHER_IP","/ics/tools/ether_ip")
epicsEnvSet("SNCSEQ","/ics/tools/seq-2.2.9")
epicsEnvSet("AUTOSAVE","/ics/tools/autosave-R5-10-2")
epicsEnvSet("ASYN","/ics/tools/asyn4-38")
epicsEnvSet("STREAM","/ics/tools/StreamDevice-master")
epicsEnvSet("BUSY","/ics/tools/busy-1-6-1")
epicsEnvSet("PVXS","/ics/tools/pvxs")
epicsEnvSet("PYDEVICE","/ics/tools/PyDevice-R1.1.1")
# PYTHONPATH points to folders where Python modules are.
epicsEnvSet("PYTHONPATH","/ics/examples/python")
cd "/ics/examples"
## Register all support components
dbLoadDatabase "dbd/pyioc.dbd"
pyioc_registerRecordDeviceDriver pdbbase
Executing Python code: import pydev
Executing Python code: import __builtin__
Executing Python code: __builtin__.pydev=pydev
## Load record instances
dbLoadRecords "db/pyioc.db", "user=training:pydevice"
dbLoadRecords "db/weather.db", "user=training"
cd "/ics/examples/iocBoot/ioc_python"
pydev "import demo"
Executing Python code: import demo
pydev "from math import *"
Executing Python code: from math import *
pydev "from weather import getWeather"
Executing Python code: from weather import getWeather
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ics/examples/python/weather.py", line 15
    url = f'{base_url}appid={api_key}&q={city}&units={units}'
                                                            ^
SyntaxError: invalid syntax
```

**Comment by klemenv** [comment]
Another missed step in the PyDevice install instructions:
```
sed -i 's/^# PYTHON_CONFIG/PYTHON_CONFIG/' /ics/tools/PyDevice-R1.1.1/configure/CONFIG_SITE
```

**Comment by klemenv** [comment]
You'll want to do make clean in PyDevice-R1.1.1 and recompile it again, followed by IOC app recompile.

**Comment by kasemir** [comment]
That did it, IOC runs now.
```
$ camonitor training:weather:temperature
training:weather:temperature   2022-01-14 12:29:40.669161 0 CALC INVALID

$ camonitor training:weather:pressure
training:weather:pressure      2022-01-14 12:20:40.887912 0 CALC INVALID
```

Is there something to do to start it?

**Comment by klemenv** [comment]
There should be a CSS screen in /ics/opi/weather.bob, and you can test out. You're welcome to try. 

But the reason for some of the troubles today was a new release of PyDevice this morning and I haven't tested everything out (a small change to use refresh.A field rather than city PV), however I wanted to have most of it in before today meeting in few minutes. I do appreciate your feedback and bug-hunting, I was also planning on proof-test it over the weekend.

**Comment by kasemir** [comment]
There is no /ics/opi/weather.bob, it's not in this PR.

**Comment by klemenv** [comment]
Just pushed another PR, you'll need to recompile the 23_pythonIOC due to a change in .db file

**Comment by kasemir** [comment]
Works!!

Screen Shot 2022-01-14 at 1 57 33 PM

**Pull request merged**
